Arduino_VESC_Library: VescPacket Class Reference
VescPacket Class Reference
class to receive and send packet
#include <vesc_packet.h>
Static Public Member Functions
static bool receive_packet (HardwareSerial *port, unsigned char *data)
receive packet from vesc
static void send_packet (HardwareSerial *port, unsigned char *data, unsigned int len)
send packet to vesc
static unsigned short crc16 (unsigned char *buf, unsigned int len)
generate crc16
Detailed Description
class to receive and send packet
Definition at line 22 of file vesc_packet.h.
Member Function Documentation
crc16()
unsigned short VescPacket::crc16 (unsigned char * buf, unsigned int len) static
generate crc16
Parameters
buf byte array
len to draw checksum
Returns
unsigned short crc16 checksum
Definition at line 168 of file vesc_packet.cpp.
References crc16_tab.
Referenced by receive_packet(), and send_packet().
receive_packet()
bool VescPacket::receive_packet (HardwareSerial * port, unsigned char * data) static
receive packet from vesc
Parameters
port to read byte array
data store received byte array
Returns
true if reading was sucessfull
false if reading gone wrong
Definition at line 80 of file vesc_packet.cpp.
References crc16().
Referenced by Vesc::receivePacket().
send_packet()
void VescPacket::send_packet (HardwareSerial * port, unsigned char * data, unsigned int len) static
send packet to vesc
Parameters
port to write byte array
data to send
len of byte array
Definition at line 30 of file vesc_packet.cpp.
References crc16().
Referenced by Vesc::sendPacket().
The documentation for this class was generated from the following files:
vesc_packet.h
vesc_packet.cpp